# Generated by https://quicktype.io
#
# To change quicktype's target language, run command:
#
#   "Set quicktype target language"

from typing import List, Optional, Dict, Union
from enum import Enum
import json


class MPrecursor:
    name: str
    composition: List[List[str]]
    formula: Optional[str]

    def __init__(self, name: str, composition: List[List[str]], formula: Optional[str]) -> None:
        self.name = name
        self.composition = composition
        self.formula = formula
    
    def __str__(self):
        return json.dumps(self.__dict__, indent=2, sort_keys=True)


class Metadatum:
    doi: Optional[str]
    title: Optional[str]
    date: Optional[str]
    journal: Optional[str]
    author_list: Optional[List[str]]

    def __init__(self, doi: Optional[str], title: Optional[str], date: Optional[str], journal: Optional[str], author_list: Optional[List[str]]) -> None:
        self.doi = doi
        self.title = title
        self.date = date
        self.journal = journal
        self.author_list = author_list
    
    def __str__(self):
        return json.dumps(self.__dict__, indent=2, sort_keys=True)


class Method(Enum):
    CONVENTIONAL_SOLVOTHERMAL = "Conventional solvothermal"
    ELECTROCHEMICAL = "Electrochemical"
    MECHANOCHEMICAL = "Mechanochemical"
    MICROWAVE = "Microwave"
    SONOCHEMICAL = "Sonochemical"


class OPrecursor:
    name: str
    composition: List[List[str]]
    smiles: Optional[str]

    def __init__(self, name: str, composition: List[List[str]], smiles: Optional[str]) -> None:
        self.name = name
        self.composition = composition
        self.smiles = smiles
    
    def __str__(self):
        return json.dumps(self.__dict__, indent=2, sort_keys=True)


class PropertyEnum(Enum):
    PRESSURE = "Pressure"
    TEMPERATURE = "Temperature"
    TIME = "Time"


class Unit(Enum):
    ATM1_0 = "atm1.0"
    BAR1_0 = "bar1.0"
    C1_0 = "°C1.0"
    D1_0 = "d1.0"
    DAY1_0 = "day1.0"
    DAYS1_0 = "days1.0"
    H1_0 = "h1.0"
    HOUR1_0 = "hour1.0"
    HOURS1_0 = "hours1.0"
    K1_0 = "K1.0"
    MBAR1_0 = "mbar1.0"
    MIN1_0 = "min1.0"
    MINUTE1_0 = "minute1.0"
    MINUTES1_0 = "minutes1.0"
    MONTH1_0 = "month1.0"
    MONTHS1_0 = "months1.0"
    M_TORR1_0 = "mTorr1.0"
    S1_0 = "s1.0"
    C_10 = "℃1.0"
    THE_10_D1_0 = "%1.0d1.0"
    TORR1_0 = "Torr1.0"
    WEEK1_0 = "week1.0"
    WEEKS1_0 = "weeks1.0"
    YEAR1_0 = "year1.0"
    DROPS1_0 = "drops1.0"
    THE_10 = "%1.0"
    WT_10 = "wt%1.0"


class Value:
    value: str
    unit: Unit

    def __init__(self, value: str, unit: Unit) -> None:
        self.value = value
        self.unit = unit
    
    def __str__(self):
        return self.value + ' ' + self.unit


class Condition:
    value: Value
    property: PropertyEnum

    def __init__(self, value: str, unit: Unit, property: PropertyEnum) -> None:
        self.value = Value(value, unit)
        self.property = property
    
    def __str__(self):
        return json.dumps(self.__dict__, indent=2, sort_keys=True)


class Name(Enum):
    COOL = "cool"
    CRYSTALLIZE = "crystallize"
    DEHYDRATE = "dehydrate"
    DIFFUSE = "diffuse"
    DISSOLVE = "dissolve"
    DRY = "dry"
    EVAPORATE = "evaporate"
    FILTER = "filter"
    GROUND = "ground"
    HEAT = "heat"
    LINSE = "linse"
    PREPARE = "prepare"
    PURIFY = "purify"
    REMOVE = "remove"
    SONICATE = "sonicate"
    STIR = "stir"
    STORE = "store"
    WAIT = "wait"
    WASH = "wash"


class Operation:
    name: Optional[Name]
    condition: List[Condition]

    def __init__(self, name: Optional[Name], condition: List[Condition]) -> None:
        self.name = name
        self.condition = condition
    
    def __str__(self):
        return json.dumps(self.__dict__, indent=2, sort_keys=True)

class Property:
    property_yield: Optional[Value]
    melting_point: Optional[Value]
    decomposition_temperature: Optional[Value]
    boiling_point: Optional[Value]

    def __init__(self, property_yield: Optional[Value], melting_point: Optional[Value], decomposition_temperature: Optional[Value], boiling_point: Optional[Value]) -> None:
        self.property_yield = property_yield
        self.melting_point = melting_point
        self.decomposition_temperature = decomposition_temperature
        self.boiling_point = boiling_point
    
    def __str__(self):
        return json.dumps(self.__dict__, indent=2, sort_keys=True)


class Solvent(Enum):
    ACETONE = "acetone"
    ACETONITRILE = "acetonitrile"
    BENZENE = "benzene"
    CHLOROFORM = "chloroform"
    DEF = "DEF"
    DICHLOROMETHANE = "dichloromethane"
    DIETHYL_ETHER = "diethyl ether"
    DMA = "DMA"
    DMF = "DMF"
    DMSO = "DMSO"
    ETHANOL = "ethanol"
    H_CL = "HCl"
    METHANOL = "methanol"
    NA_N3 = "NaN3"
    NA_OH = "NaOH"
    NITRIC_ACID = "nitric acid"
    PYRIDINE = "pyridine"
    THF = "THF"
    TRIETHYLAMINE = "triethylamine"
    WATER = "water"


class SPrecursor:
    name: str
    composition: List[List[str]]
    solvent: Optional[List[Solvent]]

    def __init__(self, name: str, composition: List[List[str]], solvent: Optional[List[Solvent]]) -> None:
        self.name = name
        self.composition = composition
        self.solvent = solvent
    
    def __str__(self):
        return json.dumps(self.__dict__, indent=2, sort_keys=True)


class SynthesisCondition:
    name: Optional[str]
    symbol: Optional[str]
    M_precursor: List[MPrecursor]
    O_precursor: List[OPrecursor]
    S_precursor: List[SPrecursor]
    MOratio: Optional[float]
    temperature: Union[List[None], Value]
    time: Union[List[None], Value]
    operation: List[Operation]
    property: Property
    method: Optional[Method]
    doi: Optional[str]
    metadata: Metadatum

    def __init__(self, name: Optional[str], symbol: Optional[str], M_precursor: List[MPrecursor], O_precursor: List[OPrecursor], S_precursor: List[SPrecursor], MOratio: Optional[float], temperature: Union[List[None], Value], time: Union[List[None], Value], operation: List[Operation], property: Property, method: Optional[Method], doi: Optional[str], metadata: Metadatum) -> None:
        self.name = name
        self.symbol = symbol
        self.M_precursor = M_precursor
        self.O_precursor = O_precursor
        self.S_precursor = S_precursor
        self.MOratio = MOratio
        self.temperature = temperature
        self.time = time
        self.operation = operation
        self.property = property
        self.method = method
        self.doi = doi
        self.metadata = metadata

    def __str__(self):
        return json.dumps(self.__dict__, indent=2, sort_keys=True)


class SynthesisConditions:
    dic: Dict[str, SynthesisCondition]

    def __init__(self, name: Dict[str, Optional[str]], symbol: Dict[str, Optional[str]], M_precursor: Dict[str, List[MPrecursor]], O_precursor: Dict[str, List[OPrecursor]], S_precursor: Dict[str, List[SPrecursor]], MOratio: Dict[str, Optional[float]], temperature: Dict[str, Union[List[None], Value]], time: Dict[str, Union[List[None], Value]], operation: Dict[str, List[Operation]], property: Dict[str, Property], method: Dict[str, Optional[Method]], doi: Dict[str, Optional[str]], metadata: Dict[str, Metadatum]) -> None:
        self.dic = {}
        for i in name.keys():
            self.dic[i] = SynthesisCondition(name[i], symbol[i], M_precursor[i], O_precursor[i], S_precursor[i], MOratio[i], temperature[i], time[i], operation[i], property[i], method[i], doi[i], metadata[i])

    def __len__(self):
        return len(self.dic)

    def __getitem__(self, ix):
        return self.dic[str(ix)]

    def __str__(self):
        return json.dumps(self.__dict__, indent=2, sort_keys=True)

