# Generated by https://quicktype.iois
#
# To change quicktype's target language, run command:
#
#   "Set quicktype target language"

from typing import List, Optional, Dict, Union
import json
from collections import defaultdict
from tqdm import tqdm
import hashlib


tostr = lambda s:  ', '.join([str(x) for x in s]) if type(s) == list else str(s)
sort_dict = lambda d: dict(sorted(d.items(), key=lambda item:item[1], reverse=True))


def format(x):
    if type(x) == str:
        x = x.replace('\u00b0C','°C').replace('℃', '°C')
        if x.endswith('1.0'):
            x = x[:-3]
        return x
    if type(x) == list:
        if len(x) == 2 and type(x[0]) == str and type(x[1]) == str:
            return format(x[0] + ' ' + x[1])
        if len(x) == 0 or x[0] is None:
            return []
        return [format(p) for p in x]
    if type(x) == dict:
        return x
    
    # print('--------------------', x, type(x))
    return x.json()


class StrClass:
    def __init__(self, **kargs):
        self.__dict__.update(**kargs)

    def __str__(self):
        assert type(self) != list
        dic = {k:str(v) for k, v in self.__dict__.items()}
        return json.dumps(dic)
    
    def __hash__(self):
        return int(hashlib.md5(str(self).encode(encoding='UTF-8')).hexdigest(), 16)

    def json(self):
        dic = self.__dict__
        delete_items = []
        for k, v in dic.items():
            if type(v) in [str, list]:
                dic[k] = format(v)
            elif 'json' not in dir(v) or not v.json() or v.json() == ' ':
                delete_items.append(k)
            else:
                # print(k, v)
                dic[k] = format(v)
        # print(delete_items)
        delete_keys(dic, *delete_items)
        if 'composition' in dic:
            dic['composition'] = ','.join(set(dic['composition']))
        delete_keys(dic, 'solvent')
        delete_keys(dic, *[k for k, v in dic.items() if not v])
        return dic


def dic2class(dic, obj):
    # print(dic, obj, type(obj))
    assert obj is not None and obj != []
    # obj = cls(*[None] * (cls.__init__.__code__.co_argcount - 1))
    
    if type(dic) == list:
        # 排除特殊情况：
        # [None, None] <__main__.Value object at 0x7f1efbae49d0> <class '__main__.Value'>
        # [] [<__main__.OPrecursor object at 0x7fe97f7257c0>] <class 'list'>
        if len(dic) and dic[0] is None: 
            return obj      # 不进行修改
        assert type(obj) == list
        cls = type(obj[0])
        # 注意这里一定要创建新的对象！！！
        if cls != list:
            return [dic2class(x, cls()) for x in dic]
        else:
            return [dic2class(x, obj[0]) for x in dic]
    elif type(dic) == dict:
        for name in dic: 
            if hasattr(obj, name):
                value = dic[name]
                if type(value) in [dict, list]:
                    assert getattr(obj, name) != []
                    value = dic2class(value, getattr(obj, name))
                setattr(obj, name, value)
            else:
                print(obj.__dict__)
                print(f'undefined at tr: {name} of {type(obj)}')
                exit(0)
        return obj
    else:
        # literal 直接返回元素本身
        return dic


class MPrecursor(StrClass):
    def __init__(self):
        self.name: str = ''
        self.composition: List[List[str]] = [['']]
        self.formula: Optional[str] = ''


class Metadatum(StrClass):
    def __init__(self):
        self.doi: Optional[str] = ''
        self.title: Optional[str] = ''
        self.date: Optional[str] = ''
        self.journal: Optional[str] = ''
        self.author_list: Optional[List[str]] = ['']

    def json(self):
        return None


class OPrecursor(StrClass):
    def __init__(self):
        self.name: str = ''
        self.composition: List[List[str]] = [['']]
        self.smiles: Optional[str] = ''

class Value(StrClass):
    def __init__(self):
        self.Value: str = ''
        self.Unit: str = ''

    def __str__(self):
        return format(self.Value + ' ' + self.Unit)

    def json(self):
        return str(self)


class Condition(StrClass):
    def __init__(self):
        self.Value: str = ''
        self.Unit: str = ''
        self.Property: str = ''

    def json(self):
        return {self.Property: format(self.Value + ' ' + self.Unit)}


class Operation(StrClass):
    def __init__(self):
        self.name: Optional[str] = ''
        self.condition: List[Condition] = [Condition()]
        # print("==========", self.condition)

    def json(self):
        # print(self.condition)
        # !!!!!!!!!!!!!!!!!!!!!!!!!!!返回值：[{'Temperature': '180 °C'}]
        dic = {}
        for t in format(self.condition):
            for k, v in t.items():
                dic[k] = v
        if self.name:
            dic['name'] = self.name
        return dic


class Property(StrClass):
    def __init__(self):
        self.Yield: Optional[Value] = Value()
        self.melting_point: Optional[Value]  = Value()
        self.decomposition_temperature: Optional[Value] = Value()
        self.boiling_point: Optional[Value] = Value()


class SPrecursor(StrClass):
    def __init__(self):
        self.name: str = ''
        self.composition: List[List[str]] = [['']]
        self.solvent: Optional[List[str]] = ['']


class SynthesisCondition(StrClass):
    def __init__(self):
        self.name: Optional[str] = ''
        self.symbol: Optional[str] = ''
        self.M_precursor: List[MPrecursor] = [MPrecursor()]
        self.O_precursor: List[OPrecursor] = [OPrecursor()]
        self.S_precursor: List[SPrecursor] = [SPrecursor()]
        self.MOratio: Optional[float] = 0.0
        self.temperature: Union[List[None], Value] = Value()
        self.time: Union[List[None], Value] = Value()
        self.operation: List[Operation] = [Operation()]
        self.Property: Property = Property()
        self.method: Optional[str] = ''
        self.doi: Optional[str] = ''
        self.metadata: Metadatum = Metadatum()

    def print(self):
        print(f'==========condition:{self.name}==========')
        for k, v in self.__dict__.items():
            print('{:15}{}'.format(k, tostr(v)))

    def get_item(self):
        pass

    def json(self):
        dic = super().json()
        if 'Property' in dic:
            for k, v in dic['Property'].items():
                dic[k] = v
        delete_keys(dic, 'Property', 'symbol')
        # delete_keys(dic, *[k for k, v in dic.items() if not v])
        return dic
        

def delete_keys(dic, *keys):
    for key in keys:
        if key in dic:
            del dic[key]


class SynthesisConditions:
    lis : List[SynthesisCondition] = []
    dic = {
        "S_precursor": defaultdict(int),
        "M_precursor": defaultdict(int),
        "O_precursor": defaultdict(int),
        "operation": defaultdict(int)
    }

    def __init__(self, path) -> None:
        import json
        with open(path, 'r') as f:
            data_str = f.read()
        data_json = json.loads(data_str.replace('yield', 'Yield').replace('property', 'Property')
                    .replace('Melting point', 'melting_point')
                    .replace('Decomposition temperature', 'decomposition_temperature')
                    .replace('Boiling point', 'boiling_point'))
        print('loading data...')
        for d in tqdm(data_json):
            # print(f'---------------------{i}----------------------')
            obj = dic2class(d, SynthesisCondition())
            # print(obj.Property)
            # exit(0)
            # if i > 1:
            #     break
            assert type(obj) == SynthesisCondition
            self.lis.append(obj)

    def __len__(self):
        return len(self.lis)

    def __getitem__(self, ix):
        return self.lis[ix]

    def generate(self):
        for m in self.lis:
            for k in ['M_precursor', "S_precursor", "O_precursor", "operation"]:
                for t in m.__dict__[k]:
                    self.dic[k][t.name] += 1

        for k in ['M_precursor', "S_precursor", "O_precursor", "operation"]:
            self.dic[k] = sort_dict(self.dic[k])

        print(self.dic)
        with open('data/precursor_info.json', 'w') as f:
            json.dump(self.dic, f, indent=2)

    def export(self):
        import pandas as pd
        precursor_df = pd.DataFrame(columns=['name', 'composition', 'mof'])
        mof_df = pd.DataFrame(columns=['name', 'paper', 'temperature', 'time', 'operation'])
        paper_df = pd.DataFrame(columns=['doi', 'journal', 'date', 'title', 'authors'])
        print('exporting data...')
        for m in tqdm(self.lis):
            for k in ['M_precursor', "S_precursor", "O_precursor"]:
                for precursor in m.__dict__[k]:
                    precursor_df.loc[len(precursor_df)] = [precursor.name, tostr(precursor.composition), m.name]
            mof_df.loc[len(mof_df)] = [m.name, m.doi, tostr(m.temperature), tostr(m.time), tostr(m.operation)]
            mm = m.metadata
            if mm.doi not in paper_df['doi']:
                paper_df.loc[len(paper_df)] = [mm.doi, mm.journal, mm.date, mm.title, tostr(mm.author_list)]
        precursor_df.to_csv('output/precursor.csv')
        mof_df.to_csv('output/mof.csv')
        paper_df.to_csv('output/paper.csv')



if __name__ == "__main__":
    conditions = SynthesisConditions('data/MOF_synthesis_condition_list.json')
    # data.generate()
    # data.export()
    for i in range(5):
        t = conditions[i]
        print(t.Property)
        print(t.json())
    # for i in range(10):
    #     a = SynthesisCondition()
    #     if i == 0:
    #         a.Property.Yield = '56 %'
    #     print(a.Property.Yield, [a], [a.Property])
    